### ISSUE TITLE
Code 2 Produces Unused arguments (Jstor_Expand)

### ISSUE THREAD

**Issue by alexisrsantos** [johnabernau/jstor_dfr#1]
Hello John, 

Thanks for answering my email. I'm running prep2.R and ... I do this ...

path <- "C:/Users/ars39/Desktop/Demography/ngram1/"
n_files <- list.files(path)

This works, and I obtain what would be expected - a string with the path and n_files is the name of teach article in the metadata. 

I then run the the function map, with the safely_jstor and it returns  a dataset with two variables (X1, and X2)

X1 is  unused arguments (word = V1, n = V2) 
X2 is  rename(., word = V1, n = V2)

My data comes from the JSTOR request where I get the metadata and the unigram (txt). 

Any help is appreciated. I tried running the function line by line (as a standalone process) and it seems the paste0 function may not be reading something correctly. 

Again, thanks!

**Comment by johnabernau** [comment]
Line 59 (paste0...) is cosmetic – it just prints the progress in the console. You can safely delete or comment-out lines 56-61. If it's still not working, make sure the file paths are correct. It looks like you're using a PC which (I believe) uses backslashes instead of forward slashes.

**Comment by alexisrsantos** [comment]
Thanks John, 

That fixed it.

Thanks
